#!/usr/bin/env tsx
// Scans src/lib/prompt-params/configs/*.ts and regenerates
// src/lib/prompt-params/configs.generated.ts as a barrel.
// File name (without .ts) is the slug.
import * as fs from 'node:fs'
import * as path from 'node:path'

const ROOT = path.resolve(__dirname, '..', '..')
const CONFIG_DIR = path.join(ROOT, 'src', 'lib', 'prompt-params', 'configs')
const OUT_FILE = path.join(ROOT, 'src', 'lib', 'prompt-params', 'configs.generated.ts')

function main() {
  const files = fs
    .readdirSync(CONFIG_DIR)
    .filter(f => f.endsWith('.ts') && !f.endsWith('.d.ts'))
    .map(f => f.replace(/\.ts$/, ''))
    .sort()

  if (files.length === 0) {
    console.error('no configs found in', CONFIG_DIR)
    process.exit(1)
  }

  const lines: string[] = []
  lines.push("// Auto-generated by `pnpm params:sync` — do not edit manually.")
  lines.push("// Add a new config by dropping a TS file in ./configs/<slug>.ts that exports `config`.")
  lines.push('')
  lines.push("import type { PromptParamsConfig } from './types'")
  files.forEach((slug, i) => {
    lines.push(`import { config as c${i} } from './configs/${slug}'`)
  })
  lines.push('')
  lines.push('export const ALL_CONFIGS: Record<string, PromptParamsConfig> = {')
  files.forEach((slug, i) => {
    lines.push(`  '${slug}': c${i},`)
  })
  lines.push('}')
  lines.push('')

  fs.writeFileSync(OUT_FILE, lines.join('\n'))
  console.log(`✓ generated ${path.relative(ROOT, OUT_FILE)} with ${files.length} configs`)
}

main()
