// @ts-nocheck
/**
 * Upload Midjourney images from Discord CDN to Vercel Blob and link to DB.
 * Reads /tmp/mj_image_urls.json (generated by Python matching script).
 *
 * Usage: npx tsx src/scripts/collect/upload-mj-images.ts
 */

import { put } from '@vercel/blob'
import { PrismaClient } from '@prisma/client'
import { readFileSync } from 'fs'

const prisma = new PrismaClient()

function log(...args: unknown[]) {
  console.error('[upload-mj]', ...args)
}

interface MatchedImage {
  slug: string
  url: string
  width: number
  height: number
}

async function main() {
  const token = process.env.BLOB_READ_WRITE_TOKEN
  if (!token) throw new Error('BLOB_READ_WRITE_TOKEN is not set')

  const data: MatchedImage[] = JSON.parse(readFileSync('/tmp/mj_image_urls.json', 'utf-8'))
  log(`Processing ${data.length} images...`)

  let success = 0
  let failed = 0

  for (const item of data) {
    log(`[${success + failed + 1}/${data.length}] ${item.slug}`)

    // Find the prompt in DB
    const prompt = await prisma.prompt.findUnique({
      where: { slug: item.slug },
      select: { id: true, images: true },
    })

    if (!prompt) {
      log(`  SKIP: prompt not found in DB`)
      failed++
      continue
    }

    if (prompt.images.length > 0) {
      log(`  SKIP: already has image`)
      continue
    }

    // Download from Discord CDN
    try {
      const resp = await fetch(item.url, { signal: AbortSignal.timeout(15000) })
      if (!resp.ok) {
        log(`  SKIP: Discord CDN returned ${resp.status}`)
        failed++
        continue
      }

      const buffer = Buffer.from(await resp.arrayBuffer())
      log(`  Downloaded: ${(buffer.length / 1024).toFixed(0)}KB`)

      // Determine extension from URL
      let ext = 'jpeg'
      try {
        const pathname = new URL(item.url).pathname
        const e = pathname.split('.').pop()?.toLowerCase()
        if (e && ['jpg', 'jpeg', 'png', 'webp'].includes(e)) ext = e
      } catch { /* ignore */ }

      const mimeType = ext === 'png' ? 'image/png' : ext === 'webp' ? 'image/webp' : 'image/jpeg'
      const fileName = `${item.slug}.${ext}`
      const blobPath = `prompts/${fileName}`

      // Upload to Vercel Blob
      const blob = await put(blobPath, buffer, {
        access: 'public',
        addRandomSuffix: true,
        contentType: mimeType,
        token,
      })

      // Create PromptImage record
      await prisma.promptImage.create({
        data: {
          promptId: prompt.id,
          url: blob.url,
          altText: null,
          order: 0,
        },
      })

      log(`  OK: ${blob.url}`)
      success++
    } catch (err) {
      log(`  ERROR:`, err instanceof Error ? err.message : err)
      failed++
    }

    // Small delay
    await new Promise(r => setTimeout(r, 500))
  }

  log(`\nDone! ${success} uploaded, ${failed} failed`)
  await prisma.$disconnect()
}

main().catch(err => {
  console.error('Fatal:', err)
  process.exit(1)
})
